# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev109+g7f05866.d20230603'
__version_tuple__ = version_tuple = (0, 1, 'dev109', 'g7f05866.d20230603')
