name: rllbc-2
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - python=3.10.8
  - pip:
    - ale_py==0.10.1
    - control==0.10.1
    - easydict==1.13
    - gymnasium==0.29.1
    - ipywidgets==8.1.5
    - jupyterlab==4.2.5
    - matplotlib==3.9.2
    - numpy==2.1.2
    - opencv-python==4.10.0.84
    - pandas==2.2.3
    - pygame==2.6.1
    - ruamel.base==1.0.0
    - ruamel.yaml==0.18.6 
    - scikit-learn==1.5.2
    - screeninfo==0.8.1
    - seaborn==0.13.2
    - setuptools==75.2.0
    - stable-baselines3==2.5.0a0 # should be replaced by a stable build when available
    - tensorboard==2.18.0
    - torch==2.3.1
    - tqdm==4.66.5 
    - wandb==0.18.3
