name: test_rllbc
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - python=3.10.8
  - pip:
    - ale_py==0.10.1
    - control==0.10.1
    - easydict==1.13
    - gymnasium==1.0.0
    - jupyterlab==4.2.5
    - matplotlib==3.9.2
    - numpy==2.1.2
    - pandas==2.2.3
    - pygame==2.6.1
    - ruamel.base==1.0.0
    - screeninfo==0.8.1
    - seaborn==0.13.2
    - setuptools==75.2.0
    - torch==2.4.1
    - tqdm==4.66.5 
    - wandb==0.18.3
